# Generated by Django 4.1.3 on 2022-12-06 03:24
from typing import Any

from django.db import migrations, transaction
from django.utils import timezone


def create_objects(apps: Any, schema_editor: Any) -> None:

    User = apps.get_model('core', 'User')
    Board = apps.get_model('goals', 'Board')
    BoardParticipant = apps.get_model('goals', 'BoardParticipant')
    Category = apps.get_model('goals', 'Category')

    with transaction.atomic():
        for user in User.objects.all():
            new_board = Board.objects.create(
                title='Мои цели',
                created=timezone.now(),
                updated=timezone.now(),
            )
            BoardParticipant.objects.create(
                user=user,
                board=new_board,
                role=1,
                created=timezone.now(),
                updated=timezone.now(),
            )
            Category.objects.filter(user=user).update(board=new_board)


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_board_category_board_boardparticipant'),
    ]

    operations = [
        migrations.RunPython(create_objects)
    ]
