# Generated by Django 4.1.3 on 2022-12-06 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_create_new_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='goals.board'),
        ),
    ]
