# Generated by Django 4.1.3 on 2022-12-13 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TgUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tg_chat_id", models.BigIntegerField(verbose_name="TG CHAT_ID")),
                (
                    "tg_user_id",
                    models.BigIntegerField(unique=True, verbose_name="TG USER_ID"),
                ),
                ("verification_code", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TG User",
                "verbose_name_plural": "TG Users",
            },
        ),
    ]
